services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=/api
    depends_on:
      - backend
    networks:
      - ai-bridge


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - OLLAMA_HOST=http://100.100.183.43:11434
    networks:
      - ai-bridge

networks:
  ai-bridge:
    name: docker_ai-bridge
    external: true
